### PR TITLE
Update variables.tf

### PR DESCRIPTION
**Pull request by dmi3x3y**
add variable "rev_request"

### CODE REVIEW

**Comment by dmi3x3y** [comment]
atlantis help

**Comment by dmi3x3** [comment]
atlantis help

**Comment by dmi3x3y** [comment]
terraform plan

**Comment by dmi3x3** [comment]
Did you mean to use `atlantis` instead of `terraform`?

**Comment by dmi3x3y** [comment]
atlantis plan

**Comment by dmi3x3** [comment]
Atlantis commands can't be run on fork pull requests. To enable, set --allow-fork-prs  or, to disable this message, set --silence-fork-pr-errors

**Comment by dmi3x3** [comment]
atlantis plan

**Comment by dmi3x3** [comment]
Atlantis commands can't be run on fork pull requests. To enable, set --allow-fork-prs  or, to disable this message, set --silence-fork-pr-errors

**Comment by dmi3x3** [comment]
terraform plan

**Comment by dmi3x3** [comment]
Did you mean to use `atlantis` instead of `terraform`?

**Comment by dmi3x3** [comment]
atlantis plan

**Comment by dmi3x3** [comment]
Atlantis commands can't be run on fork pull requests. To enable, set --allow-fork-prs  or, to disable this message, set --silence-fork-pr-errors

**Pull request merged**
