### PR TITLE
Update variables.tf

### PR DESCRIPTION
**Pull request by dmi3x3y**
rev_request set 2

### CODE REVIEW

**Comment by dmi3x3** [comment]
Atlantis commands can't be run on fork pull requests. To enable, set --allow-fork-prs  or, to disable this message, set --silence-fork-pr-errors

**Comment by dmi3x3y** [comment]
atlantis plan

**Comment by dmi3x3** [comment]
**Plan Error**
```
parsing atlantis.yaml: repo config not allowed to set 'workflow' key: server-side config needs 'allowed_overrides: [workflow]'
```

**Comment by dmi3x3y** [comment]
atlantis help

**Comment by dmi3x3** [comment]
```cmake
atlantis
Terraform Pull Request Automation

Usage:
  atlantis <command> [options] -- [terraform options]

Examples:
  # show atlantis help
  atlantis help

  # run plan in the root directory passing the -target flag to terraform
  atlantis plan -d . -- -target=resource

  # apply all unapplied plans from this pull request
  atlantis apply

  # apply the plan for the root directory and staging workspace
  atlantis apply -d . -w staging

Commands:
  plan     Runs 'terraform plan' for the changes in this pull request.
           To plan a specific project, use the -d, -w and -p flags.
  apply    Runs 'terraform apply' on all unapplied plans from this pull request.
           To only apply a specific plan, use the -d, -w and -p flags.
  unlock   Removes all atlantis locks and discards all plans for this PR.
           To unlock a specific plan you can use the Atlantis UI.
  approve_policies
           Approves all current policy checking failures for the PR.
  version  Print the output of 'terraform version'
  help     View help.

Flags:
  -h, --help   help for atlantis

Use "atlantis [command] --help" for more information about a command.
```

**Comment by dmi3x3y** [comment]
atlantis help plan

**Comment by dmi3x3** [comment]
```cmake
atlantis
Terraform Pull Request Automation

Usage:
  atlantis <command> [options] -- [terraform options]

Examples:
  # show atlantis help
  atlantis help

  # run plan in the root directory passing the -target flag to terraform
  atlantis plan -d . -- -target=resource

  # apply all unapplied plans from this pull request
  atlantis apply

  # apply the plan for the root directory and staging workspace
  atlantis apply -d . -w staging

Commands:
  plan     Runs 'terraform plan' for the changes in this pull request.
           To plan a specific project, use the -d, -w and -p flags.
  apply    Runs 'terraform apply' on all unapplied plans from this pull request.
           To only apply a specific plan, use the -d, -w and -p flags.
  unlock   Removes all atlantis locks and discards all plans for this PR.
           To unlock a specific plan you can use the Atlantis UI.
  approve_policies
           Approves all current policy checking failures for the PR.
  version  Print the output of 'terraform version'
  help     View help.

Flags:
  -h, --help   help for atlantis

Use "atlantis [command] --help" for more information about a command.
```

**Comment by dmi3x3y** [comment]
atlantis palan stage

**Comment by dmi3x3** [comment]
```
Error: unknown command "palan".
Run 'atlantis --help' for usage.
Available commands(--allow-commands): version, plan, apply, unlock, approve_policies
```

**Comment by dmi3x3y** [comment]
atlantis plan stage

**Comment by dmi3x3** [comment]
```
Error: unknown argument(s) – stage.
Usage of plan:
  -d, --dir string         Which directory to run plan in relative to root of repo,
                           ex. 'child/dir'.
  -p, --project string     Which project to run plan for. Refers to the name of the
                           project configured in a repo config file. Cannot be used
                           at same time as workspace or dir flags.
      --verbose            Append Atlantis log to comment.
  -w, --workspace string   Switch to this Terraform workspace before planning.
```

**Comment by dmi3x3y** [comment]
atlantis plan -w stage

**Comment by dmi3x3** [comment]
**Plan Error**
```
repo config not allowed to set 'workflow' key: server-side config needs 'allowed_overrides: [workflow]'
```

**Comment by dmi3x3y** [comment]
atlantis plan

**Comment by dmi3x3** [comment]
**Plan Error**
```
parsing atlantis.yaml: repo config not allowed to set 'workflow' key: server-side config needs 'allowed_overrides: [workflow]'
```

**Comment by dmi3x3y** [comment]
atlantis plan -p stage

**Comment by dmi3x3** [comment]
**Plan Error**
```
repo config not allowed to set 'workflow' key: server-side config needs 'allowed_overrides: [workflow]'
```

**Comment by dmi3x3y** [comment]
atlantis plan -p stage

**Comment by dmi3x3** [comment]
**Plan Error**
```
repo config not allowed to set 'workflow' key: server-side config needs 'allowed_overrides: [workflow]'
```

**Comment by dmi3x3y** [comment]
atlantis plan -p stage

**Comment by dmi3x3** [comment]
**Plan Error**
```
repo config not allowed to set 'workflow' key: server-side config needs 'allowed_overrides: [workflow]'
```

**Comment by dmi3x3y** [comment]
atlantis plan -p stage

**Comment by dmi3x3** [comment]
**Plan Error**
```
repo config not allowed to set 'workflow' key: server-side config needs 'allowed_overrides: [workflow]'
```

**Comment by dmi3x3y** [comment]
atlantis plan -p stage

**Comment by dmi3x3** [comment]
**Plan Error**
```
repo config not allowed to set 'workflow' key: server-side config needs 'allowed_overrides: [workflow]'
```

**Comment by dmi3x3y** [comment]
atlantis help

**Comment by dmi3x3** [comment]
```cmake
atlantis
Terraform Pull Request Automation

Usage:
  atlantis <command> [options] -- [terraform options]

Examples:
  # show atlantis help
  atlantis help

  # run plan in the root directory passing the -target flag to terraform
  atlantis plan -d . -- -target=resource

  # apply all unapplied plans from this pull request
  atlantis apply

  # apply the plan for the root directory and staging workspace
  atlantis apply -d . -w staging

Commands:
  plan     Runs 'terraform plan' for the changes in this pull request.
           To plan a specific project, use the -d, -w and -p flags.
  apply    Runs 'terraform apply' on all unapplied plans from this pull request.
           To only apply a specific plan, use the -d, -w and -p flags.
  unlock   Removes all atlantis locks and discards all plans for this PR.
           To unlock a specific plan you can use the Atlantis UI.
  approve_policies
           Approves all current policy checking failures for the PR.
  version  Print the output of 'terraform version'
  help     View help.

Flags:
  -h, --help   help for atlantis

Use "atlantis [command] --help" for more information about a command.
```

**Comment by dmi3x3y** [comment]
atlantis plan -d . -w stage

**Comment by dmi3x3** [comment]
**Plan Error**
```
repo config not allowed to set 'workflow' key: server-side config needs 'allowed_overrides: [workflow]'
```

**Comment by dmi3x3y** [comment]
atlantis plan -w stage -d .

**Comment by dmi3x3** [comment]
**Plan Error**
```
repo config not allowed to set 'workflow' key: server-side config needs 'allowed_overrides: [workflow]'
```

**Comment by dmi3x3y** [comment]
atlantis plan -w stage -d .

**Comment by dmi3x3y** [comment]
atlantis help

**Pull request closed without merging**
